version: "3.8"

services:
  fastapi-backend:
    container_name: "fastapi-backend"
    build:
      context: ./fastapi-backend-template
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  vite-react-tw-frontend:
    container_name: "vite-react-tw-frontend"
    build:
      context: ./vite-react-tw-template
      dockerfile: Dockerfile
    ports:
      - 80:80
