version: "3.8"

services:
  fastapi-backend:
    container_name: "fastapi-backend"
    build:
      context: ./fastapi-backend-template
      dockerfile: Dockerfile
    networks:
      - my-network

  vite-react-tw-frontend:
    container_name: "vite-react-tw-frontend"
    build:
      context: ./vite-react-tw-template
      dockerfile: Dockerfile
    networks:
      - my-network
    expose:
      - 80

networks:
  my-network:
    external: true